version: "3.8"

services: 

    db:
        image: mysql
        restart: always
        volumes: 
            - ${DB_FOLDER:-./src}:/docker-entrypoint-initdb.d:z
        environment: 
            MYSQL_ROOT_PASSWORD: secret
        ports: 
            - 3306:3306


    pma:
        image: phpmyadmin
        restart: always
        ports: 
            - 80:80
        environment: 
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: secret
